# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.
defaults: &defaults
  wechat_app_id: <%= ENV["WECHAT_APP_ID"] %>
  wechat_app_secret: <%= ENV["WECHAT_APP_SECRET"] %>
  weibo_app_id: <%= ENV["WEIBO_APP_ID"] %>
  weibo_app_secret: <%= ENV["WEIBO_APP_SECRET"] %>

  email:
    server_domain: qrdiy.com
    server_address: smtp.exmail.qq.com
    server_port: 465
    user_name: no-reply@qrdiy.com
    user_password: f2t*VN>Jhf4n

development:
  secret_key_base: b624573a9f9050d91050dd52b86e595db6bc6d1ea58fd5576e5db5533cf1c06ff3b8dc69bf956332860656f83ce5a5589b558f13d4983c4d1e07b2860362d200
  <<: *defaults

test:
  secret_key_base: 223e41fbbee9d4e96bd76ec12df67338893eb296134f7ddf06469b130a32f2e8449c7d619286cfce39e3df90b4b7e3804757c8af70d7d9275e96dd55bfc7e8b9
  <<: *defaults

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
