# config/app.yml for rails-settings-cached
defaults: &defaults
  exclusion:
    user:
      domain:
        - admin
        - root
      name:
        - 管理员
        - 站长

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
