# config/app.yml for rails-settings-cached
defaults: &defaults

  email_server_domain: qrdiy.com
  email_server_address: smtp.exmail.qq.com
  email_server_port: 465
  email_user_name: no-reply@qrdiy.com
  email_user_password: f2t*VN>Jhf4n

  exclusion:
    user_profile:
      domain:
        - admin
        - root
      name:
        - 管理员
        - 站长

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
